"""ids

Revision ID: 00d092749c7c
Revises: 701b8ec21a6c
Create Date: 2024-05-03 11:12:08.468965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d092749c7c'
down_revision = '701b8ec21a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('timetask', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('youtube', schema=None) as batch_op:
        batch_op.alter_column('subtopic_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube', schema=None) as batch_op:
        batch_op.alter_column('subtopic_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('timetask', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.alter_column('topic_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
