"""added field

Revision ID: 00e63d5b8d39
Revises: b82de9b93b4d
Create Date: 2024-05-14 23:17:44.350408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e63d5b8d39'
down_revision = 'b82de9b93b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('enrolled_at')

    # ### end Alembic commands ###
