"""added field

Revision ID: 019ecd873b35
Revises: ca621ad0c961
Create Date: 2024-08-15 11:12:58.670449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019ecd873b35'
down_revision = 'ca621ad0c961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_a', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.drop_column('name_a')

    # ### end Alembic commands ###
