"""duration column added

Revision ID: 072fb669427c
Revises: 
Create Date: 2024-08-01 12:40:54.896272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072fb669427c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False, server_default='3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
