"""reinvention

Revision ID: 2187fc90eb1b
Revises: a2531ab6873e
Create Date: 2024-08-14 22:28:28.850627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2187fc90eb1b'
down_revision = 'a2531ab6873e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_course_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_time_task', 'course', ['time_course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('time_course_id')

    # ### end Alembic commands ###
