"""starting from square zero

Revision ID: 2fc79f657509
Revises: 2187fc90eb1b
Create Date: 2024-08-14 23:24:16.182310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc79f657509'
down_revision = '2187fc90eb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.drop_constraint('fk_time_task', type_='foreignkey')
        batch_op.drop_column('time_course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_course_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('fk_time_task', 'course', ['time_course_id'], ['id'])

    # ### end Alembic commands ###
