"""add update_at to subtopic

Revision ID: 65418cdac036
Revises: 019ecd873b35
Create Date: 2024-08-21 20:13:22.031028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65418cdac036'
down_revision = '019ecd873b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
