"""eliminate redundant code

Revision ID: 77826adf16dd
Revises: 0c5be662fbfd
Create Date: 2024-08-05 10:38:07.823027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77826adf16dd'
down_revision = '0c5be662fbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('video_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('course', sa.VARCHAR(length=20), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
