"""course and timetask

Revision ID: 86bc163e2f8c
Revises: 2fc79f657509
Create Date: 2024-08-15 02:18:55.438459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bc163e2f8c'
down_revision = '2fc79f657509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_timetask', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetask', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
