"""remove a model

Revision ID: 95dfe50d362d
Revises: 00e63d5b8d39
Create Date: 2024-06-05 09:26:04.103968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dfe50d362d'
down_revision = '00e63d5b8d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('subtopic_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('link', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
