"""remove a Subject

Revision ID: 9690d38ad6d3
Revises: 95dfe50d362d
Create Date: 2024-06-05 09:42:57.417144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9690d38ad6d3'
down_revision = '95dfe50d362d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('subject_topics')
    op.drop_table('course_subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_subjects',
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('subject_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'subject_id')
    )
    op.create_table('subject_topics',
    sa.Column('subject_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('topic_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('subject_id', 'topic_id')
    )
    op.create_table('subject',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
