"""modifies tables

Revision ID: 9c0d3004ea34
Revises: 65418cdac036
Create Date: 2024-08-24 13:31:03.752576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0d3004ea34'
down_revision = '65418cdac036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_solution_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_subt', 'user_solution', ['user_solution_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_solution_id')

    # ### end Alembic commands ###
