"""reverse changes

Revision ID: a2531ab6873e
Revises: 4870f9687cdb
Create Date: 2024-08-14 22:21:51.644300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2531ab6873e'
down_revision = '4870f9687cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetask', schema=None) as batch_op:
        batch_op.drop_constraint('fk_time_task', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('fk_time_task', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
