"""redundant

Revision ID: c5ae7b7501ab
Revises: 6d95d4b6f16f
Create Date: 2024-08-26 11:40:43.813639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ae7b7501ab'
down_revision = '6d95d4b6f16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trialtopics_course_id', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('fk_trialtopics_course_id', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
