"""timetask and subtopic

Revision ID: ca621ad0c961
Revises: 86bc163e2f8c
Create Date: 2024-08-15 06:51:25.201154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca621ad0c961'
down_revision = '86bc163e2f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timetask_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('pk_subtopic', 'timetask', ['timetask_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtopic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('timetask_id')

    # ### end Alembic commands ###
