"""major adjust

Revision ID: e8e8dc887da7
Revises: 5d33c46f4aee
Create Date: 2024-08-25 13:44:54.054751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e8dc887da7'
down_revision = '5d33c46f4aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_solution', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
